# CRIE UM JOGO DE PAR OU ÍMPAR ONDE O COMPUTADOR IRÁ "GERAR"(VOCÊ DIGITA) UM NÚMERO ALEATÓRIO E O USUÁRIO IRÁ DIGITAR OUTRO. APÓS DIGITAR O NÚMERO, O PROGRAMA IRÁ UTILIZAR UM AFUNÇÃO PARA RESOLVER O JOGO. SE A SOMA DOS NÚMEORS FOR PAR, O USUÁRIO VENCE. SE FOR ÍMPAR, O COMPUTADOR VENCE.

